
name: Generate and Store Enriched SBOM

on:
  push:
    branches: [ master ]

jobs:
  generate-enriched-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk
        run: curl -fsSL https://snyk.io/install.sh | bash

      - name: Install Parlay
        run: |
          # Download the binary (replace with correct URL and version)
          curl -L https://snyk.github.io/parlay/releases/download/v0.5.2/parlay_Linux_x86_64.tar.gz -o parlay.tar.gz
          # Extract the binary
          tar -xzf parlay.tar.gz
          # Move the binary to PATH (Optional)
          mv parlay /usr/local/bin/

      - name: Generate SBOM
        run: snyk sbom --format cyclonedx1.4+json > sbom.json

      - name: Enrich SBOM
        run: parlay e enrich < sbom.json > enrichedSBOM.json

      - name: Upload Enriched SBOM as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: enriched-sbom
          path: enrichedSBOM.json
