
name: Generate and Store Enriched SBOM

on:
  push:
    branches: [ master ]

jobs:
  generate-enriched-sbom:
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}

      - name: Install Parlay
        run: |
          # Install Go (if not already installed)
          curl -sSL https://raw.githubusercontent.com/golang/get/master/get.sh | bash
          source /root/.bashrc  # Update PATH
          go version # Verify Go installation

          git clone https://github.com/snyk/parlay.git
          cd parlay
          go build -o parlay .
          mv parlay /usr/local/bin/  

      - name: Generate SBOM
        run: snyk sbom --format cyclonedx1.4+json > sbom.json

      - name: Enrich SBOM
        run: parlay e enrich < sbom.json > enrichedSBOM.json

      - name: Upload Enriched SBOM as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: enriched-sbom
          path: enrichedSBOM.json
