name: Snyk Test Malicious Package

on:
  push:
    branches: 
    - master

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}

      - name: Run Snyk Test
        run: snyk test --json > snyk-report.json
        continue-on-error: true

      - name: Check for Malicious Packages
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Parse Snyk Report
        run: |
          #!/usr/bin/env node
          const fs = require('fs');
          const snykReport = JSON.parse(fs.readFileSync('snyk-report.json', 'utf8'));

          let hasMaliciousPackage = false;
          for (const package of snykReport.vulnerabilities) {
            if (package.malicious === true) {
              hasMaliciousPackage = true;
              break;
            }
          }

          if (hasMaliciousPackage) {
            process.exit(1);
          }
